/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';

/**
 * 
 * @export
 * @interface AddressShared
 */
export interface AddressShared {
    /**
     * The flat number of this address
     * @type {string}
     * @memberof AddressShared
     */
    'flat_number'?: string;
    /**
     * The building number of this address
     * @type {string}
     * @memberof AddressShared
     */
    'building_number'?: string;
    /**
     * The building name of this address
     * @type {string}
     * @memberof AddressShared
     */
    'building_name'?: string;
    /**
     * The street of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'street'?: string;
    /**
     * The sub-street of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'sub_street'?: string;
    /**
     * The town of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'town'?: string;
    /**
     * The postcode or ZIP of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'postcode': string;
    /**
     * The 3 character ISO country code of this address. For example, GBR is the country code for the United Kingdom
     * @type {CountryCodes}
     * @memberof AddressShared
     */
    'country': CountryCodes;
    /**
     * The address state. US states must use the USPS abbreviation (see also ISO 3166-2:US), for example AK, CA, or TX.
     * @type {string}
     * @memberof AddressShared
     */
    'state'?: string;
    /**
     * Line 1 of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'line1'?: string | null;
    /**
     * Line 2 of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'line2'?: string | null;
    /**
     * Line 3 of the applicant\'s address
     * @type {string}
     * @memberof AddressShared
     */
    'line3'?: string | null;
}



