/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import { Location } from './location';

/**
 * 
 * @export
 * @interface ApplicantResponse
 */
export interface ApplicantResponse {
    /**
     * The unique identifier for the applicant.
     * @type {string}
     * @memberof ApplicantResponse
     */
    'id': string;
    /**
     * The date and time when this applicant was created.
     * @type {string}
     * @memberof ApplicantResponse
     */
    'created_at'?: string;
    /**
     * The date and time when this applicant is scheduled to be deleted.
     * @type {string}
     * @memberof ApplicantResponse
     */
    'delete_at'?: string;
    /**
     * The uri of this resource.
     * @type {string}
     * @memberof ApplicantResponse
     */
    'href'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicantResponse
     */
    'sandbox'?: boolean;
    /**
     * 
     * @type {Address}
     * @memberof ApplicantResponse
     */
    'address'?: Address;
    /**
     * 
     * @type {Location}
     * @memberof ApplicantResponse
     */
    'location'?: Location;
}

