/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressBuilder } from './address-builder';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicantCreate } from './applicant-create';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicantRequest } from './applicant-request';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicantShared } from './applicant-shared';
// May contain unused imports in some cases
// @ts-ignore
import { ConsentsBuilder } from './consents-builder';
// May contain unused imports in some cases
// @ts-ignore
import { IdNumber } from './id-number';
// May contain unused imports in some cases
// @ts-ignore
import { LocationBuilder } from './location-builder';

/**
 * @type ApplicantBuilder
 * @export
 */
export type ApplicantBuilder = ApplicantCreate & ApplicantRequest & ApplicantShared;


