/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdNumber } from './id-number';

/**
 * 
 * @export
 * @interface ApplicantShared
 */
export interface ApplicantShared {
    /**
     * The applicant\'s first name
     * @type {string}
     * @memberof ApplicantShared
     */
    'first_name'?: string;
    /**
     * The applicant\'s surname
     * @type {string}
     * @memberof ApplicantShared
     */
    'last_name'?: string;
    /**
     * The applicant\'s email address. Required if doing a US check, or a UK check for which `applicant_provides_data` is `true`.
     * @type {string}
     * @memberof ApplicantShared
     */
    'email'?: string;
    /**
     * The applicant\'s date of birth
     * @type {string}
     * @memberof ApplicantShared
     */
    'dob'?: string;
    /**
     * 
     * @type {Array<IdNumber>}
     * @memberof ApplicantShared
     */
    'id_numbers'?: Array<IdNumber>;
    /**
     * The applicant\'s phone number
     * @type {string}
     * @memberof ApplicantShared
     */
    'phone_number'?: string;
}

