/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicantResponse } from './applicant-response';
// May contain unused imports in some cases
// @ts-ignore
import { ApplicantShared } from './applicant-shared';
// May contain unused imports in some cases
// @ts-ignore
import { IdNumber } from './id-number';
// May contain unused imports in some cases
// @ts-ignore
import { Location } from './location';

/**
 * @type Applicant
 * @export
 */
export type Applicant = ApplicantResponse & ApplicantShared;


