/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApplicantUpdate
 */
export interface ApplicantUpdate {
    /**
     * The applicant\'s first name
     * @type {string}
     * @memberof ApplicantUpdate
     */
    'first_name'?: string;
    /**
     * The applicant\'s surname
     * @type {string}
     * @memberof ApplicantUpdate
     */
    'last_name'?: string;
}

