/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckShared
 */
export interface CheckShared {
    /**
     * An array of webhook ids describing which webhooks to trigger for this check.
     * @type {Array<string>}
     * @memberof CheckShared
     */
    'webhook_ids'?: Array<string>;
    /**
     * The ID of the applicant to do the check on.
     * @type {string}
     * @memberof CheckShared
     */
    'applicant_id': string;
    /**
     * Send an applicant form to applicant to complete to proceed with check. Defaults to false. 
     * @type {boolean}
     * @memberof CheckShared
     */
    'applicant_provides_data'?: boolean;
    /**
     * Array of tags being assigned to this check.
     * @type {Array<string>}
     * @memberof CheckShared
     */
    'tags'?: Array<string>;
    /**
     * For checks where `applicant_provides_data` is `true`, redirect to this URI when the applicant has submitted their data.
     * @type {string}
     * @memberof CheckShared
     */
    'redirect_uri'?: string;
}

