/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CheckRequest } from './check-request';
// May contain unused imports in some cases
// @ts-ignore
import { CheckShared } from './check-shared';
// May contain unused imports in some cases
// @ts-ignore
import { ReportName } from './report-name';
// May contain unused imports in some cases
// @ts-ignore
import { UsDrivingLicenceBuilder } from './us-driving-licence-builder';

/**
 * @type CheckBuilder
 * @export
 */
export type CheckBuilder = CheckRequest & CheckShared;


