/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ReportName } from './report-name';

/**
 * 
 * @export
 * @interface CheckRequest
 */
export interface CheckRequest {
    /**
     * An array of report names (strings).
     * @type {Array<ReportName>}
     * @memberof CheckRequest
     */
    'report_names'?: Array<ReportName>;
    /**
     * Optional. An array of document ids, for use with Document reports only. If omitted, the Document report will use the most recently uploaded document by default.
     * @type {Array<string>}
     * @memberof CheckRequest
     */
    'document_ids'?: Array<string>;
    /**
     * Defaults to `true`. If set to `false`, you will only receive a response when all reports in your check have completed. 
     * @type {boolean}
     * @memberof CheckRequest
     */
    'asynchronous'?: boolean;
    /**
     * For checks where `applicant_provides_data` is `true`, applicant form will not be automatically sent if `suppress_form_emails` is set to `true`. You can manually send the form at any time after the check has been created, using the link found in the form_uri attribute of the check object. Write-only. Defaults to false. 
     * @type {boolean}
     * @memberof CheckRequest
     */
    'suppress_form_emails'?: boolean;
    /**
     * Array of names of particular reports to return consider as their results. This is a feature available in sandbox testing
     * @type {Array<string>}
     * @memberof CheckRequest
     */
    'consider'?: Array<string>;
    /**
     * An object that contains all accepted fields for the Driver\'s License Data Verification report.
     * @type {{ [key: string]: any; }}
     * @memberof CheckRequest
     */
    'us_driving_licence'?: { [key: string]: any; };
}

