/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckResponse
 */
export interface CheckResponse {
    /**
     * The unique identifier for the check.
     * @type {string}
     * @memberof CheckResponse
     */
    'id': string;
    /**
     * The date and time when this check was created.
     * @type {string}
     * @memberof CheckResponse
     */
    'created_at'?: string;
    /**
     * The uri of this resource.
     * @type {string}
     * @memberof CheckResponse
     */
    'href'?: string;
    /**
     * The current state of the check in the checking process.
     * @type {string}
     * @memberof CheckResponse
     */
    'status'?: CheckResponseStatusEnum;
    /**
     * The overall result of the check, based on the results of the constituent reports.
     * @type {string}
     * @memberof CheckResponse
     */
    'result'?: CheckResponseResultEnum;
    /**
     * A link to the applicant form, if `applicant_provides_data` is `true`.
     * @type {string}
     * @memberof CheckResponse
     */
    'form_uri'?: string;
    /**
     * A link to the corresponding results page on the Onfido dashboard.
     * @type {string}
     * @memberof CheckResponse
     */
    'results_uri'?: string;
    /**
     * An array of report ids.
     * @type {Array<string>}
     * @memberof CheckResponse
     */
    'report_ids'?: Array<string>;
    /**
     * Indicates whether the object was created in the sandbox or not.
     * @type {boolean}
     * @memberof CheckResponse
     */
    'sandbox'?: boolean;
}

export const CheckResponseStatusEnum = {
    InProgress: 'in_progress',
    AwaitingApplicant: 'awaiting_applicant',
    Complete: 'complete',
    Withdrawn: 'withdrawn',
    Paused: 'paused',
    Reopened: 'reopened',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type CheckResponseStatusEnum = typeof CheckResponseStatusEnum[keyof typeof CheckResponseStatusEnum];
export const CheckResponseResultEnum = {
    Clear: 'clear',
    Consider: 'consider',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type CheckResponseResultEnum = typeof CheckResponseResultEnum[keyof typeof CheckResponseResultEnum];


