/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The applicant\'s consents
 * @export
 * @interface ConsentItem
 */
export interface ConsentItem {
    /**
     * 
     * @type {string}
     * @memberof ConsentItem
     */
    'name': ConsentItemNameEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ConsentItem
     */
    'granted': boolean;
}

export const ConsentItemNameEnum = {
    PrivacyNoticesRead: 'privacy_notices_read',
    SsnVerification: 'ssn_verification',
    PhoneNumberVerification: 'phone_number_verification',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type ConsentItemNameEnum = typeof ConsentItemNameEnum[keyof typeof ConsentItemNameEnum];


