/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';

/**
 * 
 * @export
 * @interface DeviceIntelligenceBreakdownPropertiesGeolocation
 */
export interface DeviceIntelligenceBreakdownPropertiesGeolocation {
    /**
     * City location of the IP address.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesGeolocation
     */
    'city'?: string;
    /**
     * Region location of the IP address.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesGeolocation
     */
    'region'?: string;
    /**
     * Country location of the IP address in a three letter format.
     * @type {CountryCodes}
     * @memberof DeviceIntelligenceBreakdownPropertiesGeolocation
     */
    'country'?: CountryCodes;
}



