/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceIntelligenceBreakdownPropertiesDevice
 */
export interface DeviceIntelligenceBreakdownPropertiesDevice {
    /**
     * The SDK version that was used.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'sdk_version'?: string;
    /**
     * The SDK used to upload the media.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'sdk_source'?: DeviceIntelligenceBreakdownPropertiesDeviceSdkSourceEnum;
    /**
     * The token used to authenticate the request.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'authentication_type'?: DeviceIntelligenceBreakdownPropertiesDeviceAuthenticationTypeEnum;
    /**
     * The model as set by the phone manufacturer (for Android and iOS) or the browser manufacturer (for Web). The model can be presented in name or number form depending on each manufacturer implementation.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'raw_model'?: string;
    /**
     * The operating system of the device. The value came from manufacturer implementation (for Android and iOS) or browser\'s user agent (for Web).
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'os'?: string;
    /**
     * The browser name reported by the browser\'s user agent.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'browser'?: string;
    /**
     * Whether the device is an emulator.
     * @type {boolean}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'emulator'?: boolean;
    /**
     * Whether the device is providing false randomized device and network information.
     * @type {boolean}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'randomized_device'?: boolean;
    /**
     * Whether device is using stolen security tokens to send the network information.
     * @type {boolean}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'fake_network_request'?: boolean;
    /**
     * The true operating system of the device.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     * @deprecated
     */
    'true_os'?: string;
    /**
     * The likelihood of an operating system anomaly between the true OS and the OS sent by the device.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     * @deprecated
     */
    'os_anomaly'?: string;
    /**
     * Whether the device is rooted.
     * @type {boolean}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     * @deprecated
     */
    'rooted'?: boolean;
    /**
     * Whether the device is controlled via remote software.
     * @type {boolean}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     * @deprecated
     */
    'remote_software'?: boolean;
    /**
     * Whether there is highly suspicious traffic related to the IP address. The risk depends on the overall ratio of clear checks on a given IP.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'ip_reputation'?: DeviceIntelligenceBreakdownPropertiesDeviceIpReputationEnum;
    /**
     * The number of times the device was used to create a report for a new applicant. A value greater than 1 indicates potential device reuse.
     * @type {number}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'device_fingerprint_reuse'?: number;
    /**
     * Whether the document or biometric media were uploaded from a single device.
     * @type {boolean}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'single_device_used'?: boolean | null;
    /**
     * Whether the document media were live captured from the device camera.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'document_capture'?: DeviceIntelligenceBreakdownPropertiesDeviceDocumentCaptureEnum;
    /**
     * Whether the biometric media were live captured from the device camera.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesDevice
     */
    'biometric_capture'?: DeviceIntelligenceBreakdownPropertiesDeviceBiometricCaptureEnum;
}

export const DeviceIntelligenceBreakdownPropertiesDeviceSdkSourceEnum = {
    AndroidSdk: 'onfido-android-sdk',
    IosSdk: 'onfido-ios-sdk',
    WebSdk: 'onfido-web-sdk',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DeviceIntelligenceBreakdownPropertiesDeviceSdkSourceEnum = typeof DeviceIntelligenceBreakdownPropertiesDeviceSdkSourceEnum[keyof typeof DeviceIntelligenceBreakdownPropertiesDeviceSdkSourceEnum];
export const DeviceIntelligenceBreakdownPropertiesDeviceAuthenticationTypeEnum = {
    SdkToken: 'sdk_token',
    MobileToken: 'mobile_token',
    ApiToken: 'api_token',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DeviceIntelligenceBreakdownPropertiesDeviceAuthenticationTypeEnum = typeof DeviceIntelligenceBreakdownPropertiesDeviceAuthenticationTypeEnum[keyof typeof DeviceIntelligenceBreakdownPropertiesDeviceAuthenticationTypeEnum];
export const DeviceIntelligenceBreakdownPropertiesDeviceIpReputationEnum = {
    NotEnoughData: 'NOT_ENOUGH_DATA',
    HighRisk: 'HIGH_RISK',
    LowRisk: 'LOW_RISK',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DeviceIntelligenceBreakdownPropertiesDeviceIpReputationEnum = typeof DeviceIntelligenceBreakdownPropertiesDeviceIpReputationEnum[keyof typeof DeviceIntelligenceBreakdownPropertiesDeviceIpReputationEnum];
export const DeviceIntelligenceBreakdownPropertiesDeviceDocumentCaptureEnum = {
    Live: 'live',
    UnknownMethod: 'unknown_method',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DeviceIntelligenceBreakdownPropertiesDeviceDocumentCaptureEnum = typeof DeviceIntelligenceBreakdownPropertiesDeviceDocumentCaptureEnum[keyof typeof DeviceIntelligenceBreakdownPropertiesDeviceDocumentCaptureEnum];
export const DeviceIntelligenceBreakdownPropertiesDeviceBiometricCaptureEnum = {
    Live: 'live',
    UnknownMethod: 'unknown_method',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DeviceIntelligenceBreakdownPropertiesDeviceBiometricCaptureEnum = typeof DeviceIntelligenceBreakdownPropertiesDeviceBiometricCaptureEnum[keyof typeof DeviceIntelligenceBreakdownPropertiesDeviceBiometricCaptureEnum];


