/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DeviceIntelligenceBreakdownPropertiesDevice } from './device-intelligence-breakdown-properties-device';
// May contain unused imports in some cases
// @ts-ignore
import { DeviceIntelligenceBreakdownPropertiesGeolocation } from './device-intelligence-breakdown-properties-geolocation';
// May contain unused imports in some cases
// @ts-ignore
import { DeviceIntelligenceBreakdownPropertiesIp } from './device-intelligence-breakdown-properties-ip';

/**
 * 
 * @export
 * @interface DeviceIntelligenceBreakdownProperties
 */
export interface DeviceIntelligenceBreakdownProperties {
    /**
     * 
     * @type {DeviceIntelligenceBreakdownPropertiesDevice}
     * @memberof DeviceIntelligenceBreakdownProperties
     */
    'device'?: DeviceIntelligenceBreakdownPropertiesDevice;
    /**
     * 
     * @type {DeviceIntelligenceBreakdownPropertiesIp}
     * @memberof DeviceIntelligenceBreakdownProperties
     */
    'ip'?: DeviceIntelligenceBreakdownPropertiesIp;
    /**
     * 
     * @type {DeviceIntelligenceBreakdownPropertiesGeolocation}
     * @memberof DeviceIntelligenceBreakdownProperties
     */
    'geolocation'?: DeviceIntelligenceBreakdownPropertiesGeolocation;
}

