/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceIntelligenceBreakdownPropertiesIp
 */
export interface DeviceIntelligenceBreakdownPropertiesIp {
    /**
     * The IP address that uploaded the media.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesIp
     */
    'address'?: string;
    /**
     * The likelihood of the network connection being a VPN.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesIp
     * @deprecated
     */
    'vpn_detection'?: string;
    /**
     * The likelihood of the network connection being a Proxy.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesIp
     * @deprecated
     */
    'proxy_detection'?: string;
    /**
     * The type of organization that owns this IP address.
     * @type {string}
     * @memberof DeviceIntelligenceBreakdownPropertiesIp
     * @deprecated
     */
    'type'?: string;
}

