/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner
 */
export interface DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner {
    /**
     * Vehicle class/category
     * @type {string}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner
     */
    'category'?: string;
    /**
     * Special conditions driver must meet
     * @type {string}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner
     */
    'codes'?: string;
    /**
     * Category obtainment date
     * @type {string}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner
     */
    'obtainment_date'?: string;
    /**
     * Category expiry date
     * @type {string}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner
     */
    'expiry_date'?: string;
}

