/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdown } from './document-breakdown';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentProperties } from './document-properties';
// May contain unused imports in some cases
// @ts-ignore
import { ReportDocument } from './report-document';
// May contain unused imports in some cases
// @ts-ignore
import { ReportName } from './report-name';
// May contain unused imports in some cases
// @ts-ignore
import { ReportResult } from './report-result';
// May contain unused imports in some cases
// @ts-ignore
import { ReportShared } from './report-shared';
// May contain unused imports in some cases
// @ts-ignore
import { ReportStatus } from './report-status';
// May contain unused imports in some cases
// @ts-ignore
import { ReportSubResult } from './report-sub-result';

/**
 * @type DocumentVideoWithAddressInformationReport
 * @export
 */
export type DocumentVideoWithAddressInformationReport = ReportShared;


