/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentPropertiesNfc
 */
export interface DocumentPropertiesNfc {
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'document_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'issuing_country'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'document_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'nationality'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'date_of_expiry'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'personal_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'place_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'issuing_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesNfc
     */
    'issuing_authority'?: string;
}

