/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const DocumentTypes = {
    Passport: 'passport',
    DrivingLicence: 'driving_licence',
    NationalIdentityCard: 'national_identity_card',
    ResidencePermit: 'residence_permit',
    PassportCard: 'passport_card',
    TaxId: 'tax_id',
    Visa: 'visa',
    VoterId: 'voter_id',
    ResidenceStatusDocument: 'residence_status_document',
    PostalIdentityCard: 'postal_identity_card',
    SocialSecurityCard: 'social_security_card',
    WorkPermit: 'work_permit',
    AsylumRegistrationCard: 'asylum_registration_card',
    NationalHealthInsuranceCard: 'national_health_insurance_card',
    MunicipalityIdentityCard: 'municipality_identity_card',
    PrivateOperatorsCard: 'private_operators_card',
    ProofOfCitizenship: 'proof_of_citizenship',
    ServiceIdCard: 'service_id_card',
    ImmigrationStatusDocument: 'immigration_status_document',
    IndigenousCard: 'indigenous_card',
    VehicleRegistrationCard: 'vehicle_registration_card',
    CertificateOfNaturalisation: 'certificate_of_naturalisation',
    ProfessionalQualificationCard: 'professional_qualification_card',
    ConsularId: 'consular_id',
    InternationalDrivingLicence: 'international_driving_licence',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DocumentTypes = typeof DocumentTypes[keyof typeof DocumentTypes];



