/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentPropertiesExtractedData
 */
export interface DocumentPropertiesExtractedData {
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'document_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'date_of_expiry'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'middle_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'spouse_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'widow_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'alias_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'mrz_line1'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'mrz_line2'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'mrz_line3'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'nationality'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'address_line_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'address_line_2'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'address_line_3'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'address_line_4'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'address_line_5'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesExtractedData
     */
    'issuing_authority'?: string;
}

