/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentPropertiesDrivingLicenceInformation
 */
export interface DocumentPropertiesDrivingLicenceInformation {
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDrivingLicenceInformation
     */
    'category'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDrivingLicenceInformation
     */
    'obtainment_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDrivingLicenceInformation
     */
    'expiry_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDrivingLicenceInformation
     */
    'codes'?: string;
}

