/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataComparisonBreakdownIssuingCountry } from './document-breakdown-data-comparison-breakdown-issuing-country';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataValidationBreakdownDocumentExpiration } from './document-breakdown-data-validation-breakdown-document-expiration';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataValidationBreakdownExpiryDate } from './document-breakdown-data-validation-breakdown-expiry-date';

/**
 * 
 * @export
 * @interface DocumentBreakdownDataValidationBreakdown
 */
export interface DocumentBreakdownDataValidationBreakdown {
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'gender'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'date_of_birth'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'document_numbers'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataValidationBreakdownDocumentExpiration}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'document_expiration'?: DocumentBreakdownDataValidationBreakdownDocumentExpiration;
    /**
     * 
     * @type {DocumentBreakdownDataValidationBreakdownExpiryDate}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'expiry_date'?: DocumentBreakdownDataValidationBreakdownExpiryDate;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'mrz'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataValidationBreakdown
     */
    'barcode'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
}

