/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentODPReasons
 */
export interface DocumentODPReasons {
    /**
     * When the applicant\'s document is on a physical screen or device.
     * @type {string}
     * @memberof DocumentODPReasons
     */
    'photo_of_screen'?: string;
    /**
     * When the applicant has used their mobile phone, tablet, or computer to take a photo within the device.
     * @type {string}
     * @memberof DocumentODPReasons
     */
    'screenshot'?: string;
    /**
     * When the applicant has previously captured an image of the document, printed it out, and has now taken a photo of this print out to upload.
     * @type {string}
     * @memberof DocumentODPReasons
     */
    'document_on_printed_paper'?: string;
    /**
     * When the document has clearly been captured using a scanner and there are visible indicators of this
     * @type {string}
     * @memberof DocumentODPReasons
     */
    'scan'?: string;
}

