/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownImageIntegrityBreakdownColourPicture } from './document-breakdown-image-integrity-breakdown-colour-picture';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality } from './document-breakdown-image-integrity-breakdown-conclusive-document-quality';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownImageIntegrityBreakdownImageQuality } from './document-breakdown-image-integrity-breakdown-image-quality';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownImageIntegrityBreakdownSupportedDocument } from './document-breakdown-image-integrity-breakdown-supported-document';

/**
 * 
 * @export
 * @interface DocumentBreakdownImageIntegrityBreakdown
 */
export interface DocumentBreakdownImageIntegrityBreakdown {
    /**
     * 
     * @type {DocumentBreakdownImageIntegrityBreakdownImageQuality}
     * @memberof DocumentBreakdownImageIntegrityBreakdown
     */
    'image_quality'?: DocumentBreakdownImageIntegrityBreakdownImageQuality;
    /**
     * 
     * @type {DocumentBreakdownImageIntegrityBreakdownSupportedDocument}
     * @memberof DocumentBreakdownImageIntegrityBreakdown
     */
    'supported_document'?: DocumentBreakdownImageIntegrityBreakdownSupportedDocument;
    /**
     * 
     * @type {DocumentBreakdownImageIntegrityBreakdownColourPicture}
     * @memberof DocumentBreakdownImageIntegrityBreakdown
     */
    'colour_picture'?: DocumentBreakdownImageIntegrityBreakdownColourPicture;
    /**
     * 
     * @type {DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality}
     * @memberof DocumentBreakdownImageIntegrityBreakdown
     */
    'conclusive_document_quality'?: DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality;
}

