/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesAddressLines } from './document-properties-address-lines';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesBarcodeInner } from './document-properties-barcode-inner';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesDocumentClassification } from './document-properties-document-classification';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesDocumentNumbersInner } from './document-properties-document-numbers-inner';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesDrivingLicenceInformation } from './document-properties-driving-licence-information';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesExtractedData } from './document-properties-extracted-data';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesNfc } from './document-properties-nfc';

/**
 * 
 * @export
 * @interface DocumentProperties
 */
export interface DocumentProperties {
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'date_of_expiry'?: string;
    /**
     * 
     * @type {Array<DocumentPropertiesDocumentNumbersInner>}
     * @memberof DocumentProperties
     */
    'document_numbers'?: Array<DocumentPropertiesDocumentNumbersInner>;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'document_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'issuing_country'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'nationality'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'issuing_state'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'issuing_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'categorisation'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'mrz_line1'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'mrz_line2'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'mrz_line3'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'place_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'spouse_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'widow_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'alias_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentProperties
     */
    'issuing_authority'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentProperties
     */
    'real_id_compliance'?: boolean;
    /**
     * 
     * @type {DocumentPropertiesAddressLines}
     * @memberof DocumentProperties
     */
    'address_lines'?: DocumentPropertiesAddressLines;
    /**
     * 
     * @type {Array<DocumentPropertiesBarcodeInner>}
     * @memberof DocumentProperties
     */
    'barcode'?: Array<DocumentPropertiesBarcodeInner>;
    /**
     * 
     * @type {DocumentPropertiesNfc}
     * @memberof DocumentProperties
     */
    'nfc'?: DocumentPropertiesNfc;
    /**
     * 
     * @type {DocumentPropertiesDrivingLicenceInformation}
     * @memberof DocumentProperties
     */
    'driving_licence_information'?: DocumentPropertiesDrivingLicenceInformation;
    /**
     * 
     * @type {DocumentPropertiesDocumentClassification}
     * @memberof DocumentProperties
     */
    'document_classification'?: DocumentPropertiesDocumentClassification;
    /**
     * 
     * @type {DocumentPropertiesExtractedData}
     * @memberof DocumentProperties
     */
    'extracted_data'?: DocumentPropertiesExtractedData;
}

