/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering } from './document-breakdown-visual-authenticity-breakdown-digital-tampering';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownFaceDetection } from './document-breakdown-visual-authenticity-breakdown-face-detection';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownFonts } from './document-breakdown-visual-authenticity-breakdown-fonts';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent } from './document-breakdown-visual-authenticity-breakdown-original-document-present';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownOther } from './document-breakdown-visual-authenticity-breakdown-other';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity } from './document-breakdown-visual-authenticity-breakdown-picture-face-integrity';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures } from './document-breakdown-visual-authenticity-breakdown-security-features';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticityBreakdownTemplate } from './document-breakdown-visual-authenticity-breakdown-template';

/**
 * 
 * @export
 * @interface DocumentBreakdownVisualAuthenticityBreakdown
 */
export interface DocumentBreakdownVisualAuthenticityBreakdown {
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownFonts}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'fonts'?: DocumentBreakdownVisualAuthenticityBreakdownFonts;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'picture_face_integrity'?: DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownTemplate}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'template'?: DocumentBreakdownVisualAuthenticityBreakdownTemplate;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'security_features'?: DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'original_document_present'?: DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'digital_tampering'?: DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownOther}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'other'?: DocumentBreakdownVisualAuthenticityBreakdownOther;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticityBreakdownFaceDetection}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdown
     */
    'face_detection'?: DocumentBreakdownVisualAuthenticityBreakdownFaceDetection;
}

