/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentPropertiesAddressLines
 */
export interface DocumentPropertiesAddressLines {
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesAddressLines
     */
    'street_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesAddressLines
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesAddressLines
     */
    'postal_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesAddressLines
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesAddressLines
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesAddressLines
     */
    'country_code'?: string;
}

