/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentResponse
 */
export interface DocumentResponse {
    /**
     * The unique identifier for the document
     * @type {string}
     * @memberof DocumentResponse
     */
    'id': string;
    /**
     * The date and time at which the document was uploaded
     * @type {string}
     * @memberof DocumentResponse
     */
    'created_at'?: string;
    /**
     * The uri of this resource
     * @type {string}
     * @memberof DocumentResponse
     */
    'href'?: string;
    /**
     * The uri that can be used to download the document
     * @type {string}
     * @memberof DocumentResponse
     */
    'download_href'?: string;
    /**
     * The name of the uploaded file
     * @type {string}
     * @memberof DocumentResponse
     */
    'file_name'?: string;
    /**
     * The size of the file in bytes
     * @type {number}
     * @memberof DocumentResponse
     */
    'file_size'?: number;
}

