/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataComparisonBreakdown } from './document-breakdown-data-comparison-breakdown';

/**
 * Asserts whether data on the document is consistent with data provided when creating an applicant through the API.
 * @export
 * @interface DocumentBreakdownDataComparison
 */
export interface DocumentBreakdownDataComparison {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownDataComparison
     */
    'result'?: string;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdown}
     * @memberof DocumentBreakdownDataComparison
     */
    'breakdown'?: DocumentBreakdownDataComparisonBreakdown;
}

