/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The document doesn\'t match the expected template for the document type and country it is from.
 * @export
 * @interface DocumentBreakdownVisualAuthenticityBreakdownTemplate
 */
export interface DocumentBreakdownVisualAuthenticityBreakdownTemplate {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdownTemplate
     */
    'result'?: string;
    /**
     * 
     * @type {object}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdownTemplate
     */
    'properties'?: object;
}

