/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentPropertiesBarcodeInner
 */
export interface DocumentPropertiesBarcodeInner {
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'middle_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'document_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'date_of_expiry'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'issuing_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'address_line_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'address_line_2'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'address_line_3'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'address_line_4'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'address_line_5'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'issuing_state'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'class'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'issuing_country'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'document_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesBarcodeInner
     */
    'real_id_classification'?: string;
}

