/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownImageIntegrityBreakdown } from './document-breakdown-image-integrity-breakdown';

/**
 * Asserts if the document is of sufficient quality to verify.
 * @export
 * @interface DocumentBreakdownImageIntegrity
 */
export interface DocumentBreakdownImageIntegrity {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownImageIntegrity
     */
    'result'?: string;
    /**
     * 
     * @type {DocumentBreakdownImageIntegrityBreakdown}
     * @memberof DocumentBreakdownImageIntegrity
     */
    'breakdown'?: DocumentBreakdownImageIntegrityBreakdown;
}

