/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentODPReasons } from './document-odpreasons';

/**
 * The document was not present when the photo was taken.
 * @export
 * @interface DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent
 */
export interface DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent
     */
    'result'?: string;
    /**
     * 
     * @type {DocumentODPReasons}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent
     */
    'properties'?: DocumentODPReasons;
}

