/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataConsistencyBreakdown } from './document-breakdown-data-consistency-breakdown';

/**
 * Asserts whether data represented in multiple places on the document is consistent.
 * @export
 * @interface DocumentBreakdownDataConsistency
 */
export interface DocumentBreakdownDataConsistency {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownDataConsistency
     */
    'result'?: string;
    /**
     * 
     * @type {DocumentBreakdownDataConsistencyBreakdown}
     * @memberof DocumentBreakdownDataConsistency
     */
    'breakdown'?: DocumentBreakdownDataConsistencyBreakdown;
}

