/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataComparisonBreakdownIssuingCountry } from './document-breakdown-data-comparison-breakdown-issuing-country';

/**
 * 
 * @export
 * @interface DocumentBreakdownDataComparisonBreakdown
 */
export interface DocumentBreakdownDataComparisonBreakdown {
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'issuing_country'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'gender'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'date_of_expiry'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'last_name'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'document_type'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'document_numbers'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'first_name'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof DocumentBreakdownDataComparisonBreakdown
     */
    'date_of_birth'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
}

