/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentResponse } from './document-response';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentShared } from './document-shared';

/**
 * @type Document
 * @export
 */
export type Document = DocumentResponse & DocumentShared;


