/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentProperties } from './document-properties';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesAddressLines } from './document-properties-address-lines';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesBarcodeInner } from './document-properties-barcode-inner';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesDocumentClassification } from './document-properties-document-classification';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesDocumentNumbersInner } from './document-properties-document-numbers-inner';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesDrivingLicenceInformation } from './document-properties-driving-licence-information';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesExtractedData } from './document-properties-extracted-data';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPropertiesNfc } from './document-properties-nfc';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentWithDriverVerificationReportAllOfPropertiesAllOfPassengerVehicle } from './document-with-driver-verification-report-all-of-properties-all-of-passenger-vehicle';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentWithDriverVerificationReportAllOfPropertiesAllOfVehicleClassDetailsInner } from './document-with-driver-verification-report-all-of-properties-all-of-vehicle-class-details-inner';

/**
 * @type DocumentWithDriverVerificationReportAllOfProperties
 * @export
 */
export type DocumentWithDriverVerificationReportAllOfProperties = DocumentProperties;


