/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * This sub-breakdown is returned for backward compatibility reasons. Its value will be consider when at least one of the other breakdowns is consider, and clear when all the other breakdowns are clear.
 * @export
 * @interface DocumentBreakdownVisualAuthenticityBreakdownOther
 */
export interface DocumentBreakdownVisualAuthenticityBreakdownOther {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdownOther
     */
    'result'?: string;
    /**
     * 
     * @type {object}
     * @memberof DocumentBreakdownVisualAuthenticityBreakdownOther
     */
    'properties'?: object;
}

