/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Normalised data for passenger cars
 * @export
 * @interface DocumentWithDriverVerificationReportAllOfPropertiesAllOfPassengerVehicle
 */
export interface DocumentWithDriverVerificationReportAllOfPropertiesAllOfPassengerVehicle {
    /**
     * Whether they are qualified for a passenger car, such as a “B” class in the UK
     * @type {boolean}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfPassengerVehicle
     */
    'is_qualified'?: boolean;
    /**
     * Date the class qualification was obtained
     * @type {string}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfPassengerVehicle
     */
    'obtainment_date'?: string;
    /**
     * Date the class qualification expires, which may be different to doc expiry
     * @type {string}
     * @memberof DocumentWithDriverVerificationReportAllOfPropertiesAllOfPassengerVehicle
     */
    'expiry_date'?: string;
}

