/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownAgeValidation } from './document-breakdown-age-validation';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownCompromisedDocument } from './document-breakdown-compromised-document';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataComparison } from './document-breakdown-data-comparison';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataConsistency } from './document-breakdown-data-consistency';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataValidation } from './document-breakdown-data-validation';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownImageIntegrity } from './document-breakdown-image-integrity';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownIssuingAuthority } from './document-breakdown-issuing-authority';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownPoliceRecord } from './document-breakdown-police-record';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownVisualAuthenticity } from './document-breakdown-visual-authenticity';

/**
 * 
 * @export
 * @interface DocumentBreakdown
 */
export interface DocumentBreakdown {
    /**
     * 
     * @type {DocumentBreakdownDataComparison}
     * @memberof DocumentBreakdown
     */
    'data_comparison'?: DocumentBreakdownDataComparison;
    /**
     * 
     * @type {DocumentBreakdownDataValidation}
     * @memberof DocumentBreakdown
     */
    'data_validation'?: DocumentBreakdownDataValidation;
    /**
     * 
     * @type {DocumentBreakdownImageIntegrity}
     * @memberof DocumentBreakdown
     */
    'image_integrity'?: DocumentBreakdownImageIntegrity;
    /**
     * 
     * @type {DocumentBreakdownVisualAuthenticity}
     * @memberof DocumentBreakdown
     */
    'visual_authenticity'?: DocumentBreakdownVisualAuthenticity;
    /**
     * 
     * @type {DocumentBreakdownDataConsistency}
     * @memberof DocumentBreakdown
     */
    'data_consistency'?: DocumentBreakdownDataConsistency;
    /**
     * 
     * @type {DocumentBreakdownPoliceRecord}
     * @memberof DocumentBreakdown
     */
    'police_record'?: DocumentBreakdownPoliceRecord;
    /**
     * 
     * @type {DocumentBreakdownCompromisedDocument}
     * @memberof DocumentBreakdown
     */
    'compromised_document'?: DocumentBreakdownCompromisedDocument;
    /**
     * 
     * @type {DocumentBreakdownAgeValidation}
     * @memberof DocumentBreakdown
     */
    'age_validation'?: DocumentBreakdownAgeValidation;
    /**
     * 
     * @type {DocumentBreakdownIssuingAuthority}
     * @memberof DocumentBreakdown
     */
    'issuing_authority'?: DocumentBreakdownIssuingAuthority;
}

