/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentPropertiesDocumentClassification
 */
export interface DocumentPropertiesDocumentClassification {
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDocumentClassification
     */
    'issuing_country'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDocumentClassification
     */
    'document_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPropertiesDocumentClassification
     */
    'issuing_state'?: string;
}

