/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentIQReasons } from './document-iqreasons';

/**
 * Asserts whether the quality of the image was sufficient for processing.
 * @export
 * @interface DocumentBreakdownImageIntegrityBreakdownImageQuality
 */
export interface DocumentBreakdownImageIntegrityBreakdownImageQuality {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownImageIntegrityBreakdownImageQuality
     */
    'result'?: string;
    /**
     * 
     * @type {DocumentIQReasons}
     * @memberof DocumentBreakdownImageIntegrityBreakdownImageQuality
     */
    'properties'?: DocumentIQReasons;
}

