/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';

/**
 * 
 * @export
 * @interface DocumentShared
 */
export interface DocumentShared {
    /**
     * The file type of the uploaded file
     * @type {string}
     * @memberof DocumentShared
     */
    'file_type'?: DocumentSharedFileTypeEnum;
    /**
     * The type of document
     * @type {string}
     * @memberof DocumentShared
     */
    'type'?: string;
    /**
     * The side of the document, if applicable. The possible values are front and back
     * @type {string}
     * @memberof DocumentShared
     */
    'side'?: DocumentSharedSideEnum;
    /**
     * The issuing country of the document, a 3-letter ISO code.
     * @type {CountryCodes}
     * @memberof DocumentShared
     */
    'issuing_country'?: CountryCodes;
    /**
     * The ID of the applicant whose document is being uploaded.
     * @type {string}
     * @memberof DocumentShared
     */
    'applicant_id'?: string;
}

export const DocumentSharedFileTypeEnum = {
    Jpg: 'jpg',
    Png: 'png',
    Pdf: 'pdf',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DocumentSharedFileTypeEnum = typeof DocumentSharedFileTypeEnum[keyof typeof DocumentSharedFileTypeEnum];
export const DocumentSharedSideEnum = {
    Front: 'front',
    Back: 'back',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type DocumentSharedSideEnum = typeof DocumentSharedSideEnum[keyof typeof DocumentSharedSideEnum];


