/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownCompromisedDocumentBreakdown } from './document-breakdown-compromised-document-breakdown';

/**
 * Asserts whether the image of the document has been found in our internal database or if it was used in a suspicious way.
 * @export
 * @interface DocumentBreakdownCompromisedDocument
 */
export interface DocumentBreakdownCompromisedDocument {
    /**
     * 
     * @type {string}
     * @memberof DocumentBreakdownCompromisedDocument
     */
    'result'?: string;
    /**
     * 
     * @type {DocumentBreakdownCompromisedDocumentBreakdown}
     * @memberof DocumentBreakdownCompromisedDocument
     */
    'breakdown'?: DocumentBreakdownCompromisedDocumentBreakdown;
}

