/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ErrorProperties1 } from './error-properties1';

/**
 * 
 * @export
 * @interface Error1
 */
export interface Error1 {
    /**
     * The unique identifier of the uploaded document
     * @type {string}
     * @memberof Error1
     */
    'document_id'?: string;
    /**
     * 
     * @type {ErrorProperties1}
     * @memberof Error1
     */
    'error'?: ErrorProperties1;
}

