/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentTypes } from './document-types';

/**
 * 
 * @export
 * @interface ExtractionExtractedData
 */
export interface ExtractionExtractedData {
    /**
     * The official document number.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'document_number'?: string;
    /**
     * First name.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'first_name'?: string;
    /**
     * Last name.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'last_name'?: string;
    /**
     * Full name.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'full_name'?: string;
    /**
     * Spouse name (French documents only).
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'spouse_name'?: string;
    /**
     * Widow name (French documents only).
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'widow_name'?: string;
    /**
     * Alias name (French documents only).
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'alias_name'?: string;
    /**
     * Gender (Valid values are Male and Female).
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'gender'?: ExtractionExtractedDataGenderEnum;
    /**
     * Date of birth in YYYY-MM-DD format.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'date_of_birth'?: string;
    /**
     * Date of expiry in YYYY-MM-DD format.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'date_of_expiry'?: string;
    /**
     * Date of expiry in YYYY-MM-DD format.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'expiry_date'?: string;
    /**
     * Nationality in 3-letter ISO code.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'nationality'?: string;
    /**
     * Line 1 of the MRZ code.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'mrz_line_1'?: string;
    /**
     * Line 2 of the MRZ code.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'mrz_line_2'?: string;
    /**
     * Line 3 of the MRZ code.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'mrz_line_3'?: string;
    /**
     * Line 1 of the address.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'address_1'?: string;
    /**
     * Line 2 of the address.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'address_2'?: string;
    /**
     * Line 3 of the address.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'address_3'?: string;
    /**
     * Line 4 of the address.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'address_4'?: string;
    /**
     * Line 5 of the address.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'address_5'?: string;
    /**
     * Issuing authority.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'issuing_authority'?: string;
    /**
     * Document country in 3-letter ISO code.
     * @type {CountryCodes}
     * @memberof ExtractionExtractedData
     */
    'issuing_country'?: CountryCodes;
    /**
     * Type of document.
     * @type {DocumentTypes}
     * @memberof ExtractionExtractedData
     */
    'document_type'?: DocumentTypes;
    /**
     * Place of birth.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'place_of_birth'?: string;
    /**
     * The state that issued the document.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'issuing_state'?: string;
    /**
     * Issuing date in YYYY-MM-DD format.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'issuing_date'?: string;
    /**
     * The owner\'s unique identification number.
     * @type {string}
     * @memberof ExtractionExtractedData
     */
    'personal_number'?: string;
}

export const ExtractionExtractedDataGenderEnum = {
    Male: 'Male',
    Female: 'Female',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type ExtractionExtractedDataGenderEnum = typeof ExtractionExtractedDataGenderEnum[keyof typeof ExtractionExtractedDataGenderEnum];


