/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ExtractionDocumentClassification } from './extraction-document-classification';
// May contain unused imports in some cases
// @ts-ignore
import { ExtractionExtractedData } from './extraction-extracted-data';

/**
 * 
 * @export
 * @interface Extraction
 */
export interface Extraction {
    /**
     * The unique identifier of the uploaded document.
     * @type {string}
     * @memberof Extraction
     */
    'document_id'?: string;
    /**
     * 
     * @type {ExtractionDocumentClassification}
     * @memberof Extraction
     */
    'document_classification'?: ExtractionDocumentClassification;
    /**
     * 
     * @type {ExtractionExtractedData}
     * @memberof Extraction
     */
    'extracted_data'?: ExtractionExtractedData;
}

