/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentTypes } from './document-types';

/**
 * 
 * @export
 * @interface ExtractionDocumentClassification
 */
export interface ExtractionDocumentClassification {
    /**
     * Document country in 3-letter ISO code.
     * @type {CountryCodes}
     * @memberof ExtractionDocumentClassification
     */
    'issuing_country'?: CountryCodes;
    /**
     * Type of document.
     * @type {DocumentTypes}
     * @memberof ExtractionDocumentClassification
     */
    'document_type'?: DocumentTypes;
    /**
     * The state that issued the document (if available).
     * @type {string}
     * @memberof ExtractionDocumentClassification
     */
    'issuing_state'?: string;
    /**
     * The document subtype (if available).
     * @type {string}
     * @memberof ExtractionDocumentClassification
     */
    'subtype'?: ExtractionDocumentClassificationSubtypeEnum;
    /**
     * The document issuing version (if available).
     * @type {string}
     * @memberof ExtractionDocumentClassification
     */
    'version'?: string;
}

export const ExtractionDocumentClassificationSubtypeEnum = {
    Full: 'full',
    NotFull: 'not_full',
    Provisional: 'provisional',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type ExtractionDocumentClassificationSubtypeEnum = typeof ExtractionDocumentClassificationSubtypeEnum[keyof typeof ExtractionDocumentClassificationSubtypeEnum];


