/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PhotoReasons } from './photo-reasons';

/**
 * Asserts whether the live photo is trustworthy - i.e. not digitally tampered, from a fake webcam, or from other dubious sources.
 * @export
 * @interface FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity
 */
export interface FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity {
    /**
     * 
     * @type {string}
     * @memberof FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity
     */
    'result'?: string;
    /**
     * 
     * @type {PhotoReasons}
     * @memberof FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity
     */
    'properties'?: PhotoReasons;
}

