/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownImageIntegrityBreakdownFaceDetected } from './facial-similarity-video-breakdown-image-integrity-breakdown-face-detected';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity } from './facial-similarity-video-breakdown-image-integrity-breakdown-source-integrity';

/**
 * 
 * @export
 * @interface FacialSimilarityVideoBreakdownImageIntegrityBreakdown
 */
export interface FacialSimilarityVideoBreakdownImageIntegrityBreakdown {
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownImageIntegrityBreakdownFaceDetected}
     * @memberof FacialSimilarityVideoBreakdownImageIntegrityBreakdown
     */
    'face_detected'?: FacialSimilarityVideoBreakdownImageIntegrityBreakdownFaceDetected;
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity}
     * @memberof FacialSimilarityVideoBreakdownImageIntegrityBreakdown
     */
    'source_integrity'?: FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity;
}

