/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected } from './facial-similarity-photo-breakdown-image-integrity-breakdown-face-detected';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity } from './facial-similarity-photo-fully-auto-breakdown-image-integrity-breakdown-source-integrity';

/**
 * 
 * @export
 * @interface FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown
 */
export interface FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown {
    /**
     * 
     * @type {FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected}
     * @memberof FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown
     */
    'face_detected'?: FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected;
    /**
     * 
     * @type {FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity}
     * @memberof FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown
     */
    'source_integrity'?: FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity;
}

