/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownFaceComparison } from './facial-similarity-video-breakdown-face-comparison';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownImageIntegrity } from './facial-similarity-video-breakdown-image-integrity';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownVisualAuthenticity } from './facial-similarity-video-breakdown-visual-authenticity';

/**
 * 
 * @export
 * @interface FacialSimilarityVideoBreakdown
 */
export interface FacialSimilarityVideoBreakdown {
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownFaceComparison}
     * @memberof FacialSimilarityVideoBreakdown
     */
    'face_comparison'?: FacialSimilarityVideoBreakdownFaceComparison;
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownImageIntegrity}
     * @memberof FacialSimilarityVideoBreakdown
     */
    'image_integrity'?: FacialSimilarityVideoBreakdownImageIntegrity;
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownVisualAuthenticity}
     * @memberof FacialSimilarityVideoBreakdown
     */
    'visual_authenticity'?: FacialSimilarityVideoBreakdownVisualAuthenticity;
}

