/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownImageIntegrityBreakdown } from './facial-similarity-video-breakdown-image-integrity-breakdown';

/**
 * Asserts whether the quality and integrity of the uploaded files were sufficient to perform a face comparison.
 * @export
 * @interface FacialSimilarityVideoBreakdownImageIntegrity
 */
export interface FacialSimilarityVideoBreakdownImageIntegrity {
    /**
     * 
     * @type {string}
     * @memberof FacialSimilarityVideoBreakdownImageIntegrity
     */
    'result'?: string;
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownImageIntegrityBreakdown}
     * @memberof FacialSimilarityVideoBreakdownImageIntegrity
     */
    'breakdown'?: FacialSimilarityVideoBreakdownImageIntegrityBreakdown;
}

