/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Asserts whether the numbers and head movements were correctly executed.
 * @export
 * @interface FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected
 */
export interface FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected {
    /**
     * 
     * @type {string}
     * @memberof FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected
     */
    'result'?: string;
    /**
     * 
     * @type {object}
     * @memberof FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected
     */
    'properties'?: object;
}

