/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Asserts a single face of good enough quality has been found in both the document image and the live photo.
 * @export
 * @interface FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected
 */
export interface FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected {
    /**
     * 
     * @type {string}
     * @memberof FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected
     */
    'result'?: string;
    /**
     * 
     * @type {object}
     * @memberof FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected
     */
    'properties'?: object;
}

