/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoBreakdownFaceComparison } from './facial-similarity-photo-breakdown-face-comparison';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoBreakdownVisualAuthenticity } from './facial-similarity-photo-breakdown-visual-authenticity';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity } from './facial-similarity-photo-fully-auto-breakdown-image-integrity';

/**
 * 
 * @export
 * @interface FacialSimilarityPhotoFullyAutoBreakdown
 */
export interface FacialSimilarityPhotoFullyAutoBreakdown {
    /**
     * 
     * @type {FacialSimilarityPhotoBreakdownFaceComparison}
     * @memberof FacialSimilarityPhotoFullyAutoBreakdown
     */
    'face_comparison'?: FacialSimilarityPhotoBreakdownFaceComparison;
    /**
     * 
     * @type {FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity}
     * @memberof FacialSimilarityPhotoFullyAutoBreakdown
     */
    'image_integrity'?: FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity;
    /**
     * 
     * @type {FacialSimilarityPhotoBreakdownVisualAuthenticity}
     * @memberof FacialSimilarityPhotoFullyAutoBreakdown
     */
    'visual_authenticity'?: FacialSimilarityPhotoBreakdownVisualAuthenticity;
}

