/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetectionProperties
 */
export interface FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetectionProperties {
    /**
     * A floating point number between 0 and 1. The closer the score is to 0, the more likely it is to be a spoof.
     * @type {number}
     * @memberof FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetectionProperties
     */
    'score'?: number;
}

