/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatch } from './facial-similarity-photo-breakdown-face-comparison-breakdown-face-match';

/**
 * 
 * @export
 * @interface FacialSimilarityPhotoBreakdownFaceComparisonBreakdown
 */
export interface FacialSimilarityPhotoBreakdownFaceComparisonBreakdown {
    /**
     * 
     * @type {FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatch}
     * @memberof FacialSimilarityPhotoBreakdownFaceComparisonBreakdown
     */
    'face_match'?: FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatch;
}

