/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties
 */
export interface FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
    /**
     * A floating point number between 0 and 1 that expresses how similar the two faces are, where 1 is a perfect match.
     * @type {number}
     * @memberof FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties
     */
    'score'?: number;
    /**
     * The UUID for the document containing the extracted face that was used for face matching.
     * @type {string}
     * @memberof FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties
     */
    'document_id'?: string;
}

