/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown } from './facial-similarity-video-breakdown-visual-authenticity-breakdown';

/**
 * Asserts whether the person in the live video is real (not a spoof) and live.
 * @export
 * @interface FacialSimilarityVideoBreakdownVisualAuthenticity
 */
export interface FacialSimilarityVideoBreakdownVisualAuthenticity {
    /**
     * 
     * @type {string}
     * @memberof FacialSimilarityVideoBreakdownVisualAuthenticity
     */
    'result'?: string;
    /**
     * 
     * @type {FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown}
     * @memberof FacialSimilarityVideoBreakdownVisualAuthenticity
     */
    'breakdown'?: FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown;
}

