/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownAddressBreakdownCreditAgencies } from './identity-enhanced-breakdown-address-breakdown-credit-agencies';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase } from './identity-enhanced-breakdown-address-breakdown-telephone-database';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownAddressBreakdownVotingRegister } from './identity-enhanced-breakdown-address-breakdown-voting-register';

/**
 * 
 * @export
 * @interface IdentityEnhancedBreakdownAddressBreakdown
 */
export interface IdentityEnhancedBreakdownAddressBreakdown {
    /**
     * 
     * @type {IdentityEnhancedBreakdownAddressBreakdownCreditAgencies}
     * @memberof IdentityEnhancedBreakdownAddressBreakdown
     */
    'credit_agencies'?: IdentityEnhancedBreakdownAddressBreakdownCreditAgencies;
    /**
     * 
     * @type {IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase}
     * @memberof IdentityEnhancedBreakdownAddressBreakdown
     */
    'telephone_database'?: IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase;
    /**
     * 
     * @type {IdentityEnhancedBreakdownAddressBreakdownVotingRegister}
     * @memberof IdentityEnhancedBreakdownAddressBreakdown
     */
    'voting_register'?: IdentityEnhancedBreakdownAddressBreakdownVotingRegister;
}

