/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties
 */
export interface IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties {
    /**
     * 
     * @type {number}
     * @memberof IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties
     */
    'total_number_of_sources'?: number;
}

