/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownAddressBreakdown } from './identity-enhanced-breakdown-address-breakdown';

/**
 * Asserts if the applicant\'s address matches any sources.
 * @export
 * @interface IdentityEnhancedBreakdownAddress
 */
export interface IdentityEnhancedBreakdownAddress {
    /**
     * 
     * @type {string}
     * @memberof IdentityEnhancedBreakdownAddress
     */
    'result'?: string;
    /**
     * 
     * @type {IdentityEnhancedBreakdownAddressBreakdown}
     * @memberof IdentityEnhancedBreakdownAddress
     */
    'breakdown'?: IdentityEnhancedBreakdownAddressBreakdown;
}

