/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownDateOfBirthBreakdown } from './identity-enhanced-breakdown-date-of-birth-breakdown';

/**
 * Asserts if the applicant\'s date of birth matches any sources.
 * @export
 * @interface IdentityEnhancedBreakdownDateOfBirth
 */
export interface IdentityEnhancedBreakdownDateOfBirth {
    /**
     * 
     * @type {string}
     * @memberof IdentityEnhancedBreakdownDateOfBirth
     */
    'result'?: string;
    /**
     * 
     * @type {IdentityEnhancedBreakdownDateOfBirthBreakdown}
     * @memberof IdentityEnhancedBreakdownDateOfBirth
     */
    'breakdown'?: IdentityEnhancedBreakdownDateOfBirthBreakdown;
}

