/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownDateOfBirthBreakdownCreditAgencies } from './identity-enhanced-breakdown-date-of-birth-breakdown-credit-agencies';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister } from './identity-enhanced-breakdown-date-of-birth-breakdown-voting-register';

/**
 * 
 * @export
 * @interface IdentityEnhancedBreakdownDateOfBirthBreakdown
 */
export interface IdentityEnhancedBreakdownDateOfBirthBreakdown {
    /**
     * 
     * @type {IdentityEnhancedBreakdownDateOfBirthBreakdownCreditAgencies}
     * @memberof IdentityEnhancedBreakdownDateOfBirthBreakdown
     */
    'credit_agencies'?: IdentityEnhancedBreakdownDateOfBirthBreakdownCreditAgencies;
    /**
     * 
     * @type {IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister}
     * @memberof IdentityEnhancedBreakdownDateOfBirthBreakdown
     */
    'voting_register'?: IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister;
}

