/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownAddress } from './identity-enhanced-breakdown-address';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownDateOfBirth } from './identity-enhanced-breakdown-date-of-birth';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownMortality } from './identity-enhanced-breakdown-mortality';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownSources } from './identity-enhanced-breakdown-sources';

/**
 * 
 * @export
 * @interface IdentityEnhancedBreakdown
 */
export interface IdentityEnhancedBreakdown {
    /**
     * 
     * @type {IdentityEnhancedBreakdownSources}
     * @memberof IdentityEnhancedBreakdown
     */
    'sources'?: IdentityEnhancedBreakdownSources;
    /**
     * 
     * @type {IdentityEnhancedBreakdownAddress}
     * @memberof IdentityEnhancedBreakdown
     */
    'address'?: IdentityEnhancedBreakdownAddress;
    /**
     * 
     * @type {IdentityEnhancedBreakdownDateOfBirth}
     * @memberof IdentityEnhancedBreakdown
     */
    'date_of_birth'?: IdentityEnhancedBreakdownDateOfBirth;
    /**
     * 
     * @type {IdentityEnhancedBreakdownMortality}
     * @memberof IdentityEnhancedBreakdown
     */
    'mortality'?: IdentityEnhancedBreakdownMortality;
}

