/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdentityEnhancedPropertiesMatchedAddressesInner
 */
export interface IdentityEnhancedPropertiesMatchedAddressesInner {
    /**
     * The address number.
     * @type {number}
     * @memberof IdentityEnhancedPropertiesMatchedAddressesInner
     */
    'id'?: number;
    /**
     * Sources which contain matched addresses.
     * @type {Array<string>}
     * @memberof IdentityEnhancedPropertiesMatchedAddressesInner
     */
    'match_types'?: Array<string>;
}

