/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedBreakdownSourcesBreakdownTotalSources } from './identity-enhanced-breakdown-sources-breakdown-total-sources';

/**
 * 
 * @export
 * @interface IdentityEnhancedBreakdownSourcesBreakdown
 */
export interface IdentityEnhancedBreakdownSourcesBreakdown {
    /**
     * 
     * @type {IdentityEnhancedBreakdownSourcesBreakdownTotalSources}
     * @memberof IdentityEnhancedBreakdownSourcesBreakdown
     */
    'total_sources'?: IdentityEnhancedBreakdownSourcesBreakdownTotalSources;
}

