/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IndiaPanReportAllOfBreakdownDeviceBreakdownPanValid } from './india-pan-report-all-of-breakdown-device-breakdown-pan-valid';

/**
 * 
 * @export
 * @interface IndiaPanReportAllOfBreakdownDeviceBreakdown
 */
export interface IndiaPanReportAllOfBreakdownDeviceBreakdown {
    /**
     * 
     * @type {IndiaPanReportAllOfBreakdownDeviceBreakdownPanValid}
     * @memberof IndiaPanReportAllOfBreakdownDeviceBreakdown
     */
    'pan_valid'?: IndiaPanReportAllOfBreakdownDeviceBreakdownPanValid;
    /**
     * 
     * @type {IndiaPanReportAllOfBreakdownDeviceBreakdownPanValid}
     * @memberof IndiaPanReportAllOfBreakdownDeviceBreakdown
     */
    'name_match'?: IndiaPanReportAllOfBreakdownDeviceBreakdownPanValid;
}

