/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IndiaPanReportAllOfPropertiesDevice
 */
export interface IndiaPanReportAllOfPropertiesDevice {
    /**
     * The applicant\'s PAN (10 digit alphanumeric number).
     * @type {string}
     * @memberof IndiaPanReportAllOfPropertiesDevice
     */
    'pan'?: string;
    /**
     * The applicant\'s full name.
     * @type {string}
     * @memberof IndiaPanReportAllOfPropertiesDevice
     */
    'full_name'?: string;
}

