/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Asserts whether the applicant\'s most recent facial media (live photo or live video) matches any other live photos or live videos already in your Onfido account database.
 * @export
 * @interface KnownFacesBreakdownPreviouslySeenFaces
 */
export interface KnownFacesBreakdownPreviouslySeenFaces {
    /**
     * 
     * @type {string}
     * @memberof KnownFacesBreakdownPreviouslySeenFaces
     */
    'result'?: string;
}

