/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { KnownFacesPropertiesMatchesInner } from './known-faces-properties-matches-inner';

/**
 * 
 * @export
 * @interface KnownFacesProperties
 */
export interface KnownFacesProperties {
    /**
     * Returns any matching applicant IDs as entries inside a matches array under a properties bag.
     * @type {Array<KnownFacesPropertiesMatchesInner>}
     * @memberof KnownFacesProperties
     */
    'matches'?: Array<KnownFacesPropertiesMatchesInner>;
}

