/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LivePhotoResponse
 */
export interface LivePhotoResponse {
    /**
     * The unique identifier for the photo.
     * @type {string}
     * @memberof LivePhotoResponse
     */
    'id': string;
    /**
     * The date and time at which the photo was uploaded.
     * @type {string}
     * @memberof LivePhotoResponse
     */
    'created_at'?: string;
    /**
     * The uri of this resource.
     * @type {string}
     * @memberof LivePhotoResponse
     */
    'href'?: string;
    /**
     * The uri that can be used to download the photo.
     * @type {string}
     * @memberof LivePhotoResponse
     */
    'download_href'?: string;
    /**
     * The name of the uploaded file.
     * @type {string}
     * @memberof LivePhotoResponse
     */
    'file_name'?: string;
    /**
     * The file type of the uploaded file.
     * @type {string}
     * @memberof LivePhotoResponse
     */
    'file_type'?: string;
    /**
     * The size of the file in bytes.
     * @type {number}
     * @memberof LivePhotoResponse
     */
    'file_size'?: number;
}

