/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LiveVideo
 */
export interface LiveVideo {
    /**
     * The unique identifier for the video.
     * @type {string}
     * @memberof LiveVideo
     */
    'id'?: string;
    /**
     * The date and time at which the video was uploaded.
     * @type {string}
     * @memberof LiveVideo
     */
    'created_at'?: string;
    /**
     * The uri of this resource.
     * @type {string}
     * @memberof LiveVideo
     */
    'href'?: string;
    /**
     * The uri that can be used to download the video.
     * @type {string}
     * @memberof LiveVideo
     */
    'download_href'?: string;
    /**
     * The name of the uploaded file.
     * @type {string}
     * @memberof LiveVideo
     */
    'file_name'?: string;
    /**
     * The size of the file in bytes.
     * @type {number}
     * @memberof LiveVideo
     */
    'file_size'?: number;
    /**
     * The file type of the uploaded file.
     * @type {string}
     * @memberof LiveVideo
     */
    'file_type'?: string;
    /**
     * Challenge the end user was asked to perform during the video recording.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof LiveVideo
     */
    'challenge'?: Array<{ [key: string]: any; }>;
}

