/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CountryCodes } from './country-codes';

/**
 * 
 * @export
 * @interface LocationShared
 */
export interface LocationShared {
    /**
     * The applicant\'s ip address.
     * @type {string}
     * @memberof LocationShared
     */
    'ip_address'?: string;
    /**
     * The applicant's country of residence in 3-letter ISO code.
     * @type {CountryCodes}
     * @memberof LocationShared
     */
    'country_of_residence'?: CountryCodes;
}



