/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PhotoAutoReasons
 */
export interface PhotoAutoReasons {
    /**
     * Flags when evidence is found that the image was manipulated by Photoshop, or other software.
     * @type {string}
     * @memberof PhotoAutoReasons
     */
    'digital_tampering'?: string;
    /**
     * Flags when evidence is found that a fake webcam was used.
     * @type {string}
     * @memberof PhotoAutoReasons
     */
    'fake_webcam'?: string;
    /**
     * Flags when evidence is found that the live photo was taken more than 24 hours before live photo upload.
     * @type {string}
     * @memberof PhotoAutoReasons
     */
    'time_of_capture'?: string;
    /**
     * Flags when evidence is found that an Android emulator was used.
     * @type {string}
     * @memberof PhotoAutoReasons
     */
    'emulator'?: string;
    /**
     * Additional comma separated details such as the exact digital tampering software used, or the name of the fake webcam.
     * @type {string}
     * @memberof PhotoAutoReasons
     */
    'reasons'?: string;
}

