/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressBreakdownImageIntegrityBreakdown } from './proof-of-address-breakdown-image-integrity-breakdown';

/**
 * Asserts whether the quality of the uploaded document was sufficient to verify the address.
 * @export
 * @interface ProofOfAddressBreakdownImageIntegrity
 */
export interface ProofOfAddressBreakdownImageIntegrity {
    /**
     * 
     * @type {string}
     * @memberof ProofOfAddressBreakdownImageIntegrity
     */
    'result'?: string;
    /**
     * 
     * @type {ProofOfAddressBreakdownImageIntegrityBreakdown}
     * @memberof ProofOfAddressBreakdownImageIntegrity
     */
    'breakdown'?: ProofOfAddressBreakdownImageIntegrityBreakdown;
}

