/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProofOfAddressProperties
 */
export interface ProofOfAddressProperties {
    /**
     * This property provides the address on the document.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'address'?: string;
    /**
     * This property provides the document type according to the set of supported documents.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'document_type'?: string;
    /**
     * This property provides the first names on the document, including any initials and middle names.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'first_names'?: string;
    /**
     * This property provided the last names on the document.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'last_names'?: string;
    /**
     * This property provides the issue date of the document.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'issue_date'?: string;
    /**
     * This property provides the document issuer (e.g. HSBC, British Gas).
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'issuer'?: string;
    /**
     * This property provides the summary period start date.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'summary_period_start'?: string;
    /**
     * This property provides the summary period end date.
     * @type {string}
     * @memberof ProofOfAddressProperties
     */
    'summary_period_end'?: string;
}

