/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressBreakdownDataComparison } from './proof-of-address-breakdown-data-comparison';
// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressBreakdownDocumentClassification } from './proof-of-address-breakdown-document-classification';
// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressBreakdownImageIntegrity } from './proof-of-address-breakdown-image-integrity';

/**
 * 
 * @export
 * @interface ProofOfAddressBreakdown
 */
export interface ProofOfAddressBreakdown {
    /**
     * 
     * @type {ProofOfAddressBreakdownDataComparison}
     * @memberof ProofOfAddressBreakdown
     */
    'data_comparison'?: ProofOfAddressBreakdownDataComparison;
    /**
     * 
     * @type {ProofOfAddressBreakdownDocumentClassification}
     * @memberof ProofOfAddressBreakdown
     */
    'document_classification'?: ProofOfAddressBreakdownDocumentClassification;
    /**
     * 
     * @type {ProofOfAddressBreakdownImageIntegrity}
     * @memberof ProofOfAddressBreakdown
     */
    'image_integrity'?: ProofOfAddressBreakdownImageIntegrity;
}

