/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressBreakdownDataComparisonBreakdown } from './proof-of-address-breakdown-data-comparison-breakdown';

/**
 * Asserts whether the first name, last name and address provided by the applicant match those on the PoA document.
 * @export
 * @interface ProofOfAddressBreakdownDataComparison
 */
export interface ProofOfAddressBreakdownDataComparison {
    /**
     * 
     * @type {string}
     * @memberof ProofOfAddressBreakdownDataComparison
     */
    'result'?: string;
    /**
     * 
     * @type {ProofOfAddressBreakdownDataComparisonBreakdown}
     * @memberof ProofOfAddressBreakdownDataComparison
     */
    'breakdown'?: ProofOfAddressBreakdownDataComparisonBreakdown;
}

