/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressBreakdownDocumentClassificationBreakdown } from './proof-of-address-breakdown-document-classification-breakdown';

/**
 * Asserts whether the document is of a valid type as PoA.
 * @export
 * @interface ProofOfAddressBreakdownDocumentClassification
 */
export interface ProofOfAddressBreakdownDocumentClassification {
    /**
     * 
     * @type {string}
     * @memberof ProofOfAddressBreakdownDocumentClassification
     */
    'result'?: string;
    /**
     * 
     * @type {ProofOfAddressBreakdownDocumentClassificationBreakdown}
     * @memberof ProofOfAddressBreakdownDocumentClassification
     */
    'breakdown'?: ProofOfAddressBreakdownDocumentClassificationBreakdown;
}

