/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RepeatAttemptsListRepeatAttemptsInner } from './repeat-attempts-list-repeat-attempts-inner';

/**
 * 
 * @export
 * @interface RepeatAttemptsList
 */
export interface RepeatAttemptsList {
    /**
     * The unique identifier of the completed Document report.
     * @type {string}
     * @memberof RepeatAttemptsList
     */
    'report_id'?: string;
    /**
     * An array of repeat attempt objects. If no repeat attempts were found, the array will be empty. The number of objects returned can increase over time if more matches are received. 
     * @type {Array<RepeatAttemptsListRepeatAttemptsInner>}
     * @memberof RepeatAttemptsList
     */
    'repeat_attempts': Array<RepeatAttemptsListRepeatAttemptsInner>;
    /**
     * The total number of attempts using the same document, including the current report under assessment.
     * @type {number}
     * @memberof RepeatAttemptsList
     */
    'attempts_count'?: number;
    /**
     * A number between 0 and 1 which indicates the proportion of attempts that have been cleared, including the current report under assessment.
     * @type {number}
     * @memberof RepeatAttemptsList
     */
    'attempts_clear_rate'?: number;
    /**
     * The number of unique entries in the repeat_attempts field for which at least one of the fields is a mismatch.
     * @type {number}
     * @memberof RepeatAttemptsList
     */
    'unique_mismatches_count'?: number;
}

