/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RepeatAttemptsRepeatAttemptsInner
 */
export interface RepeatAttemptsRepeatAttemptsInner {
    /**
     * The unique identifier of the matching Document report.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'report_id'?: string;
    /**
     * The unique identifier of the applicant for the matching Document report.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'applicant_id'?: string;
    /**
     * Whether the dates of birth are exactly the same or are different.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'date_of_birth'?: RepeatAttemptsRepeatAttemptsInnerDateOfBirthEnum;
    /**
     * Whether the names are exactly the same or are different.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'names'?: RepeatAttemptsRepeatAttemptsInnerNamesEnum;
    /**
     * The report result of this attempt.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'result'?: RepeatAttemptsRepeatAttemptsInnerResultEnum;
    /**
     * When the matching report was created.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'created_at'?: string;
    /**
     * When the matching report was completed.
     * @type {string}
     * @memberof RepeatAttemptsRepeatAttemptsInner
     */
    'completed_at'?: string;
}

export const RepeatAttemptsRepeatAttemptsInnerDateOfBirthEnum = {
    Match: 'match',
    Mismatch: 'mismatch',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type RepeatAttemptsRepeatAttemptsInnerDateOfBirthEnum = typeof RepeatAttemptsRepeatAttemptsInnerDateOfBirthEnum[keyof typeof RepeatAttemptsRepeatAttemptsInnerDateOfBirthEnum];
export const RepeatAttemptsRepeatAttemptsInnerNamesEnum = {
    Match: 'match',
    Mismatch: 'mismatch',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type RepeatAttemptsRepeatAttemptsInnerNamesEnum = typeof RepeatAttemptsRepeatAttemptsInnerNamesEnum[keyof typeof RepeatAttemptsRepeatAttemptsInnerNamesEnum];
export const RepeatAttemptsRepeatAttemptsInnerResultEnum = {
    Clear: 'clear',
    Consider: 'consider',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type RepeatAttemptsRepeatAttemptsInnerResultEnum = typeof RepeatAttemptsRepeatAttemptsInnerResultEnum[keyof typeof RepeatAttemptsRepeatAttemptsInnerResultEnum];


