/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RepeatAttemptsListRepeatAttemptsInner
 */
export interface RepeatAttemptsListRepeatAttemptsInner {
    /**
     * The unique identifier of the matching Document report.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'report_id'?: string;
    /**
     * The unique identifier of the applicant for the matching Document report.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'applicant_id'?: string;
    /**
     * Whether the dates of birth are exactly the same or are different.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'date_of_birth'?: RepeatAttemptsListRepeatAttemptsInnerDateOfBirthEnum;
    /**
     * Whether the names are exactly the same or are different.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'names'?: RepeatAttemptsListRepeatAttemptsInnerNamesEnum;
    /**
     * The report result of this attempt.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'result'?: RepeatAttemptsListRepeatAttemptsInnerResultEnum;
    /**
     * When the matching report was created.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'created_at'?: string;
    /**
     * When the matching report was completed.
     * @type {string}
     * @memberof RepeatAttemptsListRepeatAttemptsInner
     */
    'completed_at'?: string;
}

export const RepeatAttemptsListRepeatAttemptsInnerDateOfBirthEnum = {
    Match: 'match',
    Mismatch: 'mismatch',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type RepeatAttemptsListRepeatAttemptsInnerDateOfBirthEnum = typeof RepeatAttemptsListRepeatAttemptsInnerDateOfBirthEnum[keyof typeof RepeatAttemptsListRepeatAttemptsInnerDateOfBirthEnum];
export const RepeatAttemptsListRepeatAttemptsInnerNamesEnum = {
    Match: 'match',
    Mismatch: 'mismatch',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type RepeatAttemptsListRepeatAttemptsInnerNamesEnum = typeof RepeatAttemptsListRepeatAttemptsInnerNamesEnum[keyof typeof RepeatAttemptsListRepeatAttemptsInnerNamesEnum];
export const RepeatAttemptsListRepeatAttemptsInnerResultEnum = {
    Clear: 'clear',
    Consider: 'consider',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type RepeatAttemptsListRepeatAttemptsInnerResultEnum = typeof RepeatAttemptsListRepeatAttemptsInnerResultEnum[keyof typeof RepeatAttemptsListRepeatAttemptsInnerResultEnum];


