/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DeviceIntelligenceReport } from './device-intelligence-report';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentReport } from './document-report';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentVideoReport } from './document-video-report';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentVideoWithAddressInformationReport } from './document-video-with-address-information-report';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentWithAddressInformationReport } from './document-with-address-information-report';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentWithDriverVerificationReport } from './document-with-driver-verification-report';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentWithDrivingLicenceInformationReport } from './document-with-driving-licence-information-report';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityMotionReport } from './facial-similarity-motion-report';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoFullyAutoReport } from './facial-similarity-photo-fully-auto-report';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityPhotoReport } from './facial-similarity-photo-report';
// May contain unused imports in some cases
// @ts-ignore
import { FacialSimilarityVideoReport } from './facial-similarity-video-report';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityEnhancedReport } from './identity-enhanced-report';
// May contain unused imports in some cases
// @ts-ignore
import { IndiaPanReport } from './india-pan-report';
// May contain unused imports in some cases
// @ts-ignore
import { IndiaPanReportAllOfBreakdown } from './india-pan-report-all-of-breakdown';
// May contain unused imports in some cases
// @ts-ignore
import { IndiaPanReportAllOfProperties } from './india-pan-report-all-of-properties';
// May contain unused imports in some cases
// @ts-ignore
import { KnownFacesReport } from './known-faces-report';
// May contain unused imports in some cases
// @ts-ignore
import { ProofOfAddressReport } from './proof-of-address-report';
// May contain unused imports in some cases
// @ts-ignore
import { ReportDocument } from './report-document';
// May contain unused imports in some cases
// @ts-ignore
import { ReportName } from './report-name';
// May contain unused imports in some cases
// @ts-ignore
import { ReportResult } from './report-result';
// May contain unused imports in some cases
// @ts-ignore
import { ReportStatus } from './report-status';
// May contain unused imports in some cases
// @ts-ignore
import { ReportSubResult } from './report-sub-result';
// May contain unused imports in some cases
// @ts-ignore
import { UsDrivingLicenceReport } from './us-driving-licence-report';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistAmlReport } from './watchlist-aml-report';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistEnhancedReport } from './watchlist-enhanced-report';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistPepsOnlyReport } from './watchlist-peps-only-report';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistSanctionsOnlyReport } from './watchlist-sanctions-only-report';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistStandardReport } from './watchlist-standard-report';

/**
 * @type Report
 * @export
 */
export type Report = { name: 'device_intelligence' } & DeviceIntelligenceReport | { name: 'document' } & DocumentReport | { name: 'document_video' } & DocumentVideoReport | { name: 'document_video_with_address_information' } & DocumentVideoWithAddressInformationReport | { name: 'document_with_address_information' } & DocumentWithAddressInformationReport | { name: 'document_with_driver_verification' } & DocumentWithDriverVerificationReport | { name: 'document_with_driving_licence_information' } & DocumentWithDrivingLicenceInformationReport | { name: 'facial_similarity_motion' } & FacialSimilarityMotionReport | { name: 'facial_similarity_photo' } & FacialSimilarityPhotoReport | { name: 'facial_similarity_photo_fully_auto' } & FacialSimilarityPhotoFullyAutoReport | { name: 'facial_similarity_video' } & FacialSimilarityVideoReport | { name: 'identity_enhanced' } & IdentityEnhancedReport | { name: 'india_pan' } & IndiaPanReport | { name: 'known_faces' } & KnownFacesReport | { name: 'proof_of_address' } & ProofOfAddressReport | { name: 'us_driving_licence' } & UsDrivingLicenceReport | { name: 'watchlist_aml' } & WatchlistAmlReport | { name: 'watchlist_enhanced' } & WatchlistEnhancedReport | { name: 'watchlist_peps_only' } & WatchlistPepsOnlyReport | { name: 'watchlist_sanctions_only' } & WatchlistSanctionsOnlyReport | { name: 'watchlist_standard' } & WatchlistStandardReport;


