/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ReportDocument } from './report-document';
// May contain unused imports in some cases
// @ts-ignore
import { ReportName } from './report-name';
// May contain unused imports in some cases
// @ts-ignore
import { ReportResult } from './report-result';
// May contain unused imports in some cases
// @ts-ignore
import { ReportStatus } from './report-status';
// May contain unused imports in some cases
// @ts-ignore
import { ReportSubResult } from './report-sub-result';

/**
 * 
 * @export
 * @interface ReportShared
 */
export interface ReportShared {
    /**
     * The unique identifier for the report. Read-only.
     * @type {string}
     * @memberof ReportShared
     */
    'id': string;
    /**
     * The date and time at which the report was first initiated. Read-only.
     * @type {string}
     * @memberof ReportShared
     */
    'created_at'?: string;
    /**
     * The API endpoint to retrieve the report. Read-only.
     * @type {string}
     * @memberof ReportShared
     */
    'href'?: string;
    /**
     * 
     * @type {ReportStatus}
     * @memberof ReportShared
     */
    'status'?: ReportStatus;
    /**
     * 
     * @type {ReportResult}
     * @memberof ReportShared
     */
    'result'?: ReportResult;
    /**
     * 
     * @type {ReportSubResult}
     * @memberof ReportShared
     */
    'sub_result'?: ReportSubResult;
    /**
     * The ID of the check to which the report belongs. Read-only.
     * @type {string}
     * @memberof ReportShared
     */
    'check_id'?: string;
    /**
     * Array of objects with document ids that were used in the Onfido engine. [ONLY POPULATED FOR DOCUMENT AND FACIAL SIMILARITY REPORTS]
     * @type {Array<ReportDocument>}
     * @memberof ReportShared
     */
    'documents'?: Array<ReportDocument>;
    /**
     * 
     * @type {ReportName}
     * @memberof ReportShared
     */
    'name': ReportName;
}



