/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * The identifier for the Task.
     * @type {string}
     * @memberof Task
     */
    'id'?: string;
    /**
     * The identifier for the Task Definition.
     * @type {string}
     * @memberof Task
     */
    'task_def_id'?: string;
    /**
     * The date and time when the Task was created.
     * @type {string}
     * @memberof Task
     */
    'created_at'?: string;
    /**
     * The date and time when the Task was last updated.
     * @type {string}
     * @memberof Task
     */
    'updated_at'?: string;
}

