/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataComparisonBreakdownIssuingCountry } from './document-breakdown-data-comparison-breakdown-issuing-country';

/**
 * 
 * @export
 * @interface UsDrivingLicenceBreakdownPersonalBreakdown
 */
export interface UsDrivingLicenceBreakdownPersonalBreakdown {
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'first_name'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'name_suffix'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'height'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'weight'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'sex_code'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'eye_color'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'date_of_birth'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'last_name'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'middle_name'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'first_name_fuzzy'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'middle_name_fuzzy'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'last_name_fuzzy'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownPersonalBreakdown
     */
    'middle_initial'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
}

