/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBreakdownDataComparisonBreakdownIssuingCountry } from './document-breakdown-data-comparison-breakdown-issuing-country';

/**
 * 
 * @export
 * @interface UsDrivingLicenceBreakdownAddressBreakdown
 */
export interface UsDrivingLicenceBreakdownAddressBreakdown {
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownAddressBreakdown
     */
    'city'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownAddressBreakdown
     */
    'line_1'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownAddressBreakdown
     */
    'line_2'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownAddressBreakdown
     */
    'state_code'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownAddressBreakdown
     */
    'zip4'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
    /**
     * 
     * @type {DocumentBreakdownDataComparisonBreakdownIssuingCountry}
     * @memberof UsDrivingLicenceBreakdownAddressBreakdown
     */
    'zip5'?: DocumentBreakdownDataComparisonBreakdownIssuingCountry;
}

