/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An object that contains all accepted fields for the Driver\'s License Data Verification report.
 * @export
 * @interface UsDrivingLicenceShared
 */
export interface UsDrivingLicenceShared {
    /**
     * Driving licence ID number
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'id_number': string;
    /**
     * Two letter code of issuing state (state-issued driving licenses only)
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'issue_state': string;
    /**
     * Line 1 of the address
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'address_line_1'?: string;
    /**
     * Line 2 of the address
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'address_line_2'?: string;
    /**
     * The city of the owner\'s address
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'city'?: string;
    /**
     * Date of birth in yyyy-mm-dd format
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'date_of_birth'?: string;
    /**
     * Document category.
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'document_category'?: UsDrivingLicenceSharedDocumentCategoryEnum;
    /**
     * Expiration date of the driving licence in yyyy-mm-dd format
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'expiration_date'?: string;
    /**
     * Eye color code.
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'eye_color_code'?: UsDrivingLicenceSharedEyeColorCodeEnum;
    /**
     * The owner\'s first name
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'gender'?: UsDrivingLicenceSharedGenderEnum;
    /**
     * Issue date in yyyy-mm-dd format
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'issue_date'?: string;
    /**
     * The owner\'s surname
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'last_name'?: string;
    /**
     * The owner\'s middle name
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'middle_name'?: string;
    /**
     * The owner\'s name suffix
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'name_suffix'?: string;
    /**
     * The postcode or ZIP of the owner\'s address
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'postal_code'?: string;
    /**
     * 2-characters state code
     * @type {string}
     * @memberof UsDrivingLicenceShared
     */
    'state'?: string;
    /**
     * Weight in pounds
     * @type {number}
     * @memberof UsDrivingLicenceShared
     */
    'weight_measure'?: number;
}

export const UsDrivingLicenceSharedDocumentCategoryEnum = {
    DriverLicense: 'driver license',
    DriverPermit: 'driver permit',
    IdCard: 'id card',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type UsDrivingLicenceSharedDocumentCategoryEnum = typeof UsDrivingLicenceSharedDocumentCategoryEnum[keyof typeof UsDrivingLicenceSharedDocumentCategoryEnum];
export const UsDrivingLicenceSharedEyeColorCodeEnum = {
    Blk: 'BLK',
    Blu: 'BLU',
    Bro: 'BRO',
    Dic: 'DIC',
    Gry: 'GRY',
    Grn: 'GRN',
    Haz: 'HAZ',
    Mar: 'MAR',
    Pnk: 'PNK',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type UsDrivingLicenceSharedEyeColorCodeEnum = typeof UsDrivingLicenceSharedEyeColorCodeEnum[keyof typeof UsDrivingLicenceSharedEyeColorCodeEnum];
export const UsDrivingLicenceSharedGenderEnum = {
    Male: 'Male',
    Female: 'Female',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type UsDrivingLicenceSharedGenderEnum = typeof UsDrivingLicenceSharedGenderEnum[keyof typeof UsDrivingLicenceSharedGenderEnum];


