/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UsDrivingLicenceBreakdownAddress } from './us-driving-licence-breakdown-address';
// May contain unused imports in some cases
// @ts-ignore
import { UsDrivingLicenceBreakdownDocument } from './us-driving-licence-breakdown-document';
// May contain unused imports in some cases
// @ts-ignore
import { UsDrivingLicenceBreakdownPersonal } from './us-driving-licence-breakdown-personal';

/**
 * 
 * @export
 * @interface UsDrivingLicenceBreakdown
 */
export interface UsDrivingLicenceBreakdown {
    /**
     * 
     * @type {UsDrivingLicenceBreakdownDocument}
     * @memberof UsDrivingLicenceBreakdown
     */
    'document'?: UsDrivingLicenceBreakdownDocument;
    /**
     * 
     * @type {UsDrivingLicenceBreakdownAddress}
     * @memberof UsDrivingLicenceBreakdown
     */
    'address'?: UsDrivingLicenceBreakdownAddress;
    /**
     * 
     * @type {UsDrivingLicenceBreakdownPersonal}
     * @memberof UsDrivingLicenceBreakdown
     */
    'personal'?: UsDrivingLicenceBreakdownPersonal;
}

