/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WatchlistMonitor
 */
export interface WatchlistMonitor {
    /**
     * The unique identifier for the monitor.
     * @type {string}
     * @memberof WatchlistMonitor
     */
    'id'?: string;
    /**
     * The date and time at which the monitor was created.
     * @type {string}
     * @memberof WatchlistMonitor
     */
    'created_at'?: string;
    /**
     * The date and time at which the monitor was deleted. If the monitor is still active, this field will be null.
     * @type {string}
     * @memberof WatchlistMonitor
     */
    'deleted_at'?: string;
    /**
     * The ID for the applicant associated with the monitor.
     * @type {string}
     * @memberof WatchlistMonitor
     */
    'applicant_id': string;
    /**
     * The name of the report type the monitor creates. Can be either \"watchlist_standard\" or \"watchlist_aml\".
     * @type {string}
     * @memberof WatchlistMonitor
     */
    'report_name': WatchlistMonitorReportNameEnum;
    /**
     * A list of tags associated with this monitor. These tags will be applied to each check this monitor creates.
     * @type {Array<string>}
     * @memberof WatchlistMonitor
     */
    'tags'?: Array<string>;
    /**
     * Indicates whether the object was created in the sandbox or not.
     * @type {boolean}
     * @memberof WatchlistMonitor
     */
    'sandbox'?: boolean;
}

export const WatchlistMonitorReportNameEnum = {
    Standard: 'watchlist_standard',
    Aml: 'watchlist_aml',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type WatchlistMonitorReportNameEnum = typeof WatchlistMonitorReportNameEnum[keyof typeof WatchlistMonitorReportNameEnum];


