/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Asserts if there are any records found of negative events reported by publicly and generally available media sources.
 * @export
 * @interface WatchlistAmlBreakdownAdverseMedia
 */
export interface WatchlistAmlBreakdownAdverseMedia {
    /**
     * 
     * @type {string}
     * @memberof WatchlistAmlBreakdownAdverseMedia
     */
    'result'?: string;
}

