/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WatchlistMonitorMatch
 */
export interface WatchlistMonitorMatch {
    /**
     * Monitor ID
     * @type {string}
     * @memberof WatchlistMonitorMatch
     */
    'id'?: string;
    /**
     * Monitor status
     * @type {boolean}
     * @memberof WatchlistMonitorMatch
     */
    'status'?: boolean;
}

