/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Asserts if there are any records found in Law-Enforcement and Regulatory bodies Monitored Lists (including Terrorism, Money Laundering and Most Wanted lists).
 * @export
 * @interface WatchlistAmlBreakdownLegalAndRegulatoryWarnings
 */
export interface WatchlistAmlBreakdownLegalAndRegulatoryWarnings {
    /**
     * 
     * @type {string}
     * @memberof WatchlistAmlBreakdownLegalAndRegulatoryWarnings
     */
    'result'?: string;
}

