/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WatchlistAmlBreakdownAdverseMedia } from './watchlist-aml-breakdown-adverse-media';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistAmlBreakdownLegalAndRegulatoryWarnings } from './watchlist-aml-breakdown-legal-and-regulatory-warnings';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistAmlBreakdownPoliticallyExposedPerson } from './watchlist-aml-breakdown-politically-exposed-person';
// May contain unused imports in some cases
// @ts-ignore
import { WatchlistAmlBreakdownSanction } from './watchlist-aml-breakdown-sanction';

/**
 * 
 * @export
 * @interface WatchlistEnhancedBreakdown
 */
export interface WatchlistEnhancedBreakdown {
    /**
     * 
     * @type {WatchlistAmlBreakdownPoliticallyExposedPerson}
     * @memberof WatchlistEnhancedBreakdown
     */
    'politically_exposed_person'?: WatchlistAmlBreakdownPoliticallyExposedPerson;
    /**
     * 
     * @type {WatchlistAmlBreakdownSanction}
     * @memberof WatchlistEnhancedBreakdown
     */
    'sanction'?: WatchlistAmlBreakdownSanction;
    /**
     * 
     * @type {WatchlistAmlBreakdownAdverseMedia}
     * @memberof WatchlistEnhancedBreakdown
     */
    'adverse_media'?: WatchlistAmlBreakdownAdverseMedia;
    /**
     * 
     * @type {WatchlistAmlBreakdownLegalAndRegulatoryWarnings}
     * @memberof WatchlistEnhancedBreakdown
     */
    'monitored_lists'?: WatchlistAmlBreakdownLegalAndRegulatoryWarnings;
}

