/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WatchlistEnhancedProperties
 */
export interface WatchlistEnhancedProperties {
    /**
     * Returns any matches including, but not limited to, name and date of birth of match, aliases and associates, and relevant events and sources.
     * @type {Array<string>}
     * @memberof WatchlistEnhancedProperties
     */
    'records'?: Array<string>;
}

