/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WebhookEventType } from './webhook-event-type';

/**
 * 
 * @export
 * @interface WebhooksResendItem
 */
export interface WebhooksResendItem {
    /**
     * ID of the resource whose webhooks are to be retriggered.
     * @type {string}
     * @memberof WebhooksResendItem
     */
    'resource_id': string;
    /**
     * The events that should retrigger webhooks. Accepts values check.completed.
     * @type {WebhookEventType}
     * @memberof WebhooksResendItem
     */
    'event': WebhookEventType;
}



