/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WebhookEventPayloadObject } from './webhook-event-payload-object';
// May contain unused imports in some cases
// @ts-ignore
import { WebhookEventType } from './webhook-event-type';

/**
 * 
 * @export
 * @interface WebhookEventPayload
 */
export interface WebhookEventPayload {
    /**
     * Indicates the resource affected by this event.
     * @type {string}
     * @memberof WebhookEventPayload
     */
    'resource_type': string;
    /**
     * The event that triggered this webhook.
     * @type {WebhookEventType}
     * @memberof WebhookEventPayload
     */
    'action'?: WebhookEventType;
    /**
     * 
     * @type {WebhookEventPayloadObject}
     * @memberof WebhookEventPayload
     */
    'object'?: WebhookEventPayloadObject;
    /**
     * The resource affected by this event.
     * @type {object}
     * @memberof WebhookEventPayload
     */
    'resource'?: object;
}



