/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const WebhookEventType = {
    AuditLogCreated: 'audit_log.created',
    WatchlistMonitorMatchesUpdated: 'watchlist_monitor.matches_updated',
    WorkflowRunCompleted: 'workflow_run.completed',
    WorkflowTaskStarted: 'workflow_task.started',
    WorkflowTaskCompleted: 'workflow_task.completed',
    CheckStarted: 'check.started',
    CheckReopened: 'check.reopened',
    CheckWithdrawn: 'check.withdrawn',
    CheckCompleted: 'check.completed',
    CheckFormCompleted: 'check.form_completed',
    ReportWithdrawn: 'report.withdrawn',
    ReportResumed: 'report.resumed',
    ReportCancelled: 'report.cancelled',
    ReportAwaitingApproval: 'report.awaiting_approval',
    ReportCompleted: 'report.completed',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type WebhookEventType = typeof WebhookEventType[keyof typeof WebhookEventType];



