/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Webhook } from './webhook';

/**
 * 
 * @export
 * @interface WebhooksList
 */
export interface WebhooksList {
    /**
     * 
     * @type {Array<Webhook>}
     * @memberof WebhooksList
     */
    'webhooks'?: Array<Webhook>;
}

