/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebhookResendDataInner
 */
export interface WebhookResendDataInner {
    /**
     * Type of resource to retrigger webhooks. Accepts values check.
     * @type {string}
     * @memberof WebhookResendDataInner
     */
    'resource_type': string;
    /**
     * ID of the resource whose webhooks are to be retriggered.
     * @type {string}
     * @memberof WebhookResendDataInner
     */
    'resource_id': string;
    /**
     * The events that should retrigger webhooks. Accepts values check.completed.
     * @type {string}
     * @memberof WebhookResendDataInner
     */
    'event': WebhookResendDataInnerEventEnum;
}

export const WebhookResendDataInnerEventEnum = {
    CheckCompleted: 'check.completed',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type WebhookResendDataInnerEventEnum = typeof WebhookResendDataInnerEventEnum[keyof typeof WebhookResendDataInnerEventEnum];


