/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WorkflowRunResponse } from './workflow-run-response';
// May contain unused imports in some cases
// @ts-ignore
import { WorkflowRunResponseError } from './workflow-run-response-error';
// May contain unused imports in some cases
// @ts-ignore
import { WorkflowRunShared } from './workflow-run-shared';
// May contain unused imports in some cases
// @ts-ignore
import { WorkflowRunSharedLink } from './workflow-run-shared-link';

/**
 * @type WorkflowRun
 * @export
 */
export type WorkflowRun = WorkflowRunResponse & WorkflowRunShared;


