/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowRunRequest
 */
export interface WorkflowRunRequest {
    /**
     * Object with Custom Input Data to be used in the Workflow Run.
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowRunRequest
     */
    'custom_data'?: { [key: string]: any; };
}

