/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WorkflowRunResponseError } from './workflow-run-response-error';

/**
 * 
 * @export
 * @interface WorkflowRunResponse
 */
export interface WorkflowRunResponse {
    /**
     * The unique identifier for the Workflow Run.
     * @type {string}
     * @memberof WorkflowRunResponse
     */
    'id': string;
    /**
     * The identifier for the Workflow version.
     * @type {number}
     * @memberof WorkflowRunResponse
     */
    'workflow_version_id'?: number;
    /**
     * The URL for viewing the Workflow Run results on your Onfido Dashboard.
     * @type {string}
     * @memberof WorkflowRunResponse
     */
    'dashboard_url'?: string;
    /**
     * The status of the Workflow Run.
     * @type {string}
     * @memberof WorkflowRunResponse
     */
    'status'?: WorkflowRunResponseStatusEnum;
    /**
     * Output object contains all of the properties configured on the Workflow version.
     * @type {object}
     * @memberof WorkflowRunResponse
     */
    'output'?: object;
    /**
     * The reasons the Workflow Run outcome was reached. Configurable when creating the Workflow version.
     * @type {Array<string>}
     * @memberof WorkflowRunResponse
     */
    'reasons'?: Array<string>;
    /**
     * 
     * @type {WorkflowRunResponseError}
     * @memberof WorkflowRunResponse
     */
    'error'?: WorkflowRunResponseError;
}

export const WorkflowRunResponseStatusEnum = {
    AwaitingInput: 'awaiting_input',
    Processing: 'processing',
    Abandoned: 'abandoned',
    Error: 'error',
    Approved: 'approved',
    Review: 'review',
    Declined: 'declined',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type WorkflowRunResponseStatusEnum = typeof WorkflowRunResponseStatusEnum[keyof typeof WorkflowRunResponseStatusEnum];


