/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Error object. Only set when the Workflow Run status is \'error\'.
 * @export
 * @interface WorkflowRunResponseError
 */
export interface WorkflowRunResponseError {
    /**
     * The type of error.
     * @type {string}
     * @memberof WorkflowRunResponseError
     */
    'type'?: string;
    /**
     * A textual description of the error.
     * @type {string}
     * @memberof WorkflowRunResponseError
     */
    'message'?: string;
}

