/* tslint:disable */
/* eslint-disable */
/**
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WorkflowRunSharedLink } from './workflow-run-shared-link';

/**
 * 
 * @export
 * @interface WorkflowRunShared
 */
export interface WorkflowRunShared {
    /**
     * The unique identifier for the Applicant.
     * @type {string}
     * @memberof WorkflowRunShared
     */
    'applicant_id': string;
    /**
     * The unique identifier for the Workflow.
     * @type {string}
     * @memberof WorkflowRunShared
     */
    'workflow_id': string;
    /**
     * Tags or labels assigned to the workflow run.
     * @type {Array<string>}
     * @memberof WorkflowRunShared
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {WorkflowRunSharedLink}
     * @memberof WorkflowRunShared
     */
    'link'?: WorkflowRunSharedLink;
    /**
     * The date and time when the Workflow Run was created.
     * @type {string}
     * @memberof WorkflowRunShared
     */
    'created_at'?: string;
    /**
     * The date and time when the Workflow Run was last updated.
     * @type {string}
     * @memberof WorkflowRunShared
     */
    'updated_at'?: string;
}

