/* tslint:disable */
/* eslint-disable */
/**
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BASE_PATH } from "./base";
import axios from 'axios';

export enum Region{
    EU,
    US,
    CA
}

export interface ConfigurationParameters {
    apiToken?: string;
    oauthClientId?: string;
    oauthClientSecret?: string;
    region?: Region;
    basePath?: string;
    baseOptions?: any;
    formDataCtor?: new () => any;
}

export class Configuration {
    /**
     * parameter for apiKey security
     * @param name security name
     */
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    /**
     * parameter for basic security
     */
    username?: string;
    /**
     * parameter for basic security
     */
    password?: string;
    /**
     * parameter for oauth2 security
     * @param name security name
     * @param scopes oauth2 scope
     */
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    /**
     * override base path
     */
    basePath?: string;
    /**
     * override server index
     */
    serverIndex?: number;
    /**
     * base options for axios calls
     */
    baseOptions?: any;
    /**
     * The FormData constructor that will be used to create multipart form data
     * requests. You can inject this here so that execution environments that
     * do not support the FormData class can still run the generated client.
     *
     * @type {new () => FormData}
     */
    formDataCtor?: new () => any;

    private _oauthTokenUrl?: string;
    private _oauthClientId?: string;
    private _oauthClientSecret?: string;
    private _cachedAccessToken?: string;
    private _tokenExpiresAt?: number;
    private _tokenRefreshPromise?: Promise<string>;

    constructor(param: ConfigurationParameters = {}) {
        const hasApiToken = !!param.apiToken;
        const hasPartialOAuth = !!(param.oauthClientId || param.oauthClientSecret);
        const hasOAuth = !!(param.oauthClientId && param.oauthClientSecret);

        if (hasPartialOAuth && !hasOAuth) {
            throw new Error("Both oauthClientId and oauthClientSecret must be provided together");
        }

        if (!hasApiToken && !hasOAuth) {
            throw new Error("No apiToken or OAuth credentials (oauthClientId + oauthClientSecret) provided");
        }

        if (hasApiToken && hasOAuth) {
            throw new Error("Provide either apiToken or OAuth credentials (oauthClientId + oauthClientSecret), not both");
        }

        if (param.region && !Object.values(Region).includes(param.region)) {
            throw new Error(`Unknown or missing region '${param.region}'`);
        }

        const regionStr = Region[param.region || Region.EU].toLowerCase();
        this.basePath = param.basePath || BASE_PATH.replace('.eu.', `.${regionStr}.`)

        if (hasApiToken) {
            this.apiKey = 'Token token=' + param.apiToken;
        } else {
            this._oauthClientId = param.oauthClientId;
            this._oauthClientSecret = param.oauthClientSecret;
            this._oauthTokenUrl = this.basePath + '/oauth/token';
            this.accessToken = async () => this._getOAuthAccessToken();
        }

        this.baseOptions = {...{ timeout: 30_000 },
                            ...param.baseOptions,
            headers: {...param.baseOptions?.headers,
                'User-Agent': "onfido-node/6.1.0"
            },
        };
        this.formDataCtor = param.formDataCtor || require('form-data');         // Injiect form data constructor (if needed)
    }

    /**
     * Fetches and caches an OAuth2 access token using the client credentials flow.
     * Automatically refreshes the token when it expires (with a 30-second buffer).
     */
    private async _getOAuthAccessToken(): Promise<string> {
        const now = Date.now();
        if (this._cachedAccessToken && this._tokenExpiresAt && now < this._tokenExpiresAt) {
            return this._cachedAccessToken;
        }

        if (this._tokenRefreshPromise) {
            return this._tokenRefreshPromise;
        }

        this._tokenRefreshPromise = this._fetchOAuthToken();
        try {
            return await this._tokenRefreshPromise;
        } finally {
            this._tokenRefreshPromise = undefined;
        }
    }

    /**
     * Performs the actual token exchange via POST to the OAuth2 token endpoint.
     */
    private async _fetchOAuthToken(): Promise<string> {
        const response = await axios.post(
            this._oauthTokenUrl!,
            new URLSearchParams({
                grant_type: 'client_credentials',
                client_id: this._oauthClientId!,
                client_secret: this._oauthClientSecret!,
            }).toString(),
            {
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                timeout: 30_000,
            },
        );

        const { access_token, expires_in } = response.data;
        if (!access_token) {
            throw new Error('OAuth2 token response did not contain an access_token');
        }

        this._cachedAccessToken = access_token;
        this._tokenExpiresAt = Date.now() + ((expires_in || 3600) - 30) * 1000;
        return access_token;
    }

    /**
     * Check if the given MIME is a JSON MIME.
     * JSON MIME examples:
     *   application/json
     *   application/json; charset=UTF8
     *   APPLICATION/JSON
     *   application/vnd.company+json
     * @param mime - MIME (Multipurpose Internet Mail Extensions)
     * @return True if the given MIME is JSON, false otherwise.
     */
    public isJsonMime(mime: string): boolean {
        const jsonMime: RegExp = new RegExp('^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$', 'i');
        return mime !== null && (jsonMime.test(mime) || mime.toLowerCase() === 'application/json-patch+json');
    }
}
